platzigram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('', include('posts.urls', namespace='posts')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import PostListView, PostCreateView, PostDetailView

app_name = "posts"

urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    path('posts/new', PostCreateView.as_view(), name="create"),
    path('posts/<int:pk>', PostDetailView.as_view(), name="detail")
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.views import SignUpView, UpdateProfile, ProfileDetailView
from django.contrib.auth.views import LoginView

app_name = "users"

urlpatterns = [
    path('login/', LoginView.as_view(
        template_name="users/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('users/me/profile/', UpdateProfile.as_view(), name="update_profile"),
    path('<str:username>', ProfileDetailView.as_view(), name="detail_profile"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title} by @{self.user.username}'

users/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class Profile(models.Model):
    """Profile model.
    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'photo')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as UserForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from users. models import Profile

class UserCreationForm(UserForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control', 
                'placeholder': ' '.join(name.split('_')).title()
            })

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
            raise forms.ValidationError(_("A user with this email already exists."))
        except User.DoesNotExist:
            pass
        return self.cleaned_data['email']


class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        exclude = ('user',)

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from posts.models import Post
from posts.forms import PostForm
from django.urls import reverse_lazy
# Create your views here.


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    ordering = ('-created_at',)
    paginate_by = 30


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('posts:list')

    def form_valid(self, form):
        _object = form.save(commit=False)
        _object.user = self.request.user
        _object.profile = self.request.user.profile
        self.object = _object.save()
        return super(PostCreateView, self).form_valid(form)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import FormView, CreateView, UpdateView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from users.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from users import models, forms
from posts.models import Post
# Create your views here.


class SignUpView(CreateView):
    model = User
    template_name = "users/user_form.html"
    form_class = UserCreationForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        _object = form.save()
        models.Profile.objects.create(user=_object)
        return super(SignUpView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, UpdateView):
    model = models.Profile
    form_class = forms.ProfileForm
    template_name = 'users/update_profile.html'
    # success_url = reverse_lazy('users:update_profile')

    def get_object(self):
        return self.request.user.profile

    def get_success_url(self):
        return reverse_lazy('users:detail_profile', args=(self.object.user.username,))


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile_detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        """Add user's posts to context."""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(
            user=user).order_by('-created_at')
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:list' %}">
            <img src="{% static 'img/instagram.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail_profile' request.user.username %}">
                        {% if request.user.profile.picture.url %}
                        <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail_profile" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}"
                alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <p class="mt-1 ml-2">
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created_at }}</small>
    </p>
</div>

templates/posts/post_detail.html
{% extends "base.html" %}

{% block head_content %}
<title>Platzigram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

<div class="container">
    <div class="row">
        {% include "posts/post_card.html" %}
    </div>
</div>

{% endblock %}

templates/posts/post_form.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>
                {% if form.errors %}
                <p class="alert alert-danger">
                    {% for field in form %}
                    {% if field.errors %}
                    {{ field.label }}:
                    {% for error in field.errors %}
                    {{ error }} <br>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </p>
                {% endif %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
          
                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_list.html
{% extends "base.html" %}

{% block head_content %}
<title>Platzigram</title>
{% endblock%}

{% block container %}
<div class="container">
    <div class="row">

        {% for post in object_list %}
        <div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
            <div class="media pt-3 pl-3 pb-1">
                <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}"
                    alt="{{ post.user.get_full_name }}">
                <div class="media-body">
                    <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                </div>
            </div>

            <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

            <p class="mt-1 ml-2">
                <a href="" style="color: #000; font-size: 20px;">
                    <i class="far fa-heart"></i>
                </a> 30 likes
            </p>
            <p class="ml-2 mt-0 mb-2">
                <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <a href="{% url 'users:login' %}">
                    <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">
                </a>

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign in</title>
{% endblock%}

{% block container %}

{% if form.errors %}
<p class="alert alert-danger">Username or Password not match... Try Again</p>
{% endif%}

<form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}

    <div class="form-group">
        <input class="form-control" type="text" placeholder="Username" name="username" />
    </div>

    <div class="form-group">
        <input class="form-control" type="password" placeholder="Password" name="password" />
    </div>


    <button class="btn btn-primary btn-block mt-4" type="submit">Sign in!</button>

</form>
<p class="mt-4">Don't have an account yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>

{% endblock %}

templates/users/profile_detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">

        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" style="height: 100%; width: 100%;"/>
        </div>

        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{ user.username }}
                {% if user == request.user %}
                <a href="{% url "users:update_profile" %}" class="ml-5 btn btn-sm btn-outline-info">
                    Edit profile
                </a>
                {% else %}
                <a href="" class="ml-5 btn btn-sm btn-primary">
                    Follow
                </a>
                {% endif %}
            </h2>

            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
            <a href="{% url 'posts:detail' post.pk %}" class="border">
                <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid" />
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b>{{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input class="form-control {% if form.website.errors %}is-invalid{% endif %}" type="text"
                        name="website" placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                        {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Biography field #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                        {{ error }}
                        {% endfor%}
                    </div>
                </div>

                {# Phone number field #}
                <div class="form-group">
                    <label>Phone number</label>
                    <input class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}" type="text"
                        name="phone_number" placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}" />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                        {{ error }}
                        {% endfor%}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/user_form.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram Sign Up</title>
{% endblock%}

{% block container %}

{% if form.errors %}
<p class="alert alert-danger">
    {% for field in form %}
        {% if field.errors %}
            {{ field.label }}:
            {% for error in field.errors %}
                {{ error }} <br>
            {% endfor %}
        {% endif %}
    {% endfor %}
</p>
{% endif %}

<form method="POST">
    {% csrf_token %}

    {% for i in form %}
        <div class="form-group">
        {{ i }}
        </div>
    {% endfor %}
    <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

</form>

{% endblock %}